name: Build and Push Docker Image to Github Container Registry
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest --tag spencershepard/xmrig-d:latest

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push spencershepard/xmrig-d:latest